# Numpy exercises

1. Import the numpy package under the name np

 hint: import … as

In [37]:
import numpy as np

Create a null vector of size 10 

hint: np.zeros

In [38]:
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1

hint: array[4]

In [39]:
null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

hint: arange

In [40]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8

hint: reshape

In [41]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

hint: np.nonzero

In [42]:
elements = [1, 2, 0, 0, 4, 0]

arr = np.array(elements)

non_zero = np.nonzero(arr)

print(non_zero)


(array([0, 1, 4]),)


Create a 3x3 identity matrix

hint: np.eye

In [43]:
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

hint: np.random.random

In [44]:
array = np.random.random((3, 3, 3))

print(array)

[[[0.88766517 0.228694   0.7760802 ]
  [0.91319433 0.2296263  0.44543883]
  [0.88696273 0.94890799 0.56218279]]

 [[0.61929474 0.15089364 0.99154817]
  [0.33607636 0.89771796 0.6738765 ]
  [0.15881203 0.48747924 0.88390598]]

 [[0.37523015 0.16556093 0.39079158]
  [0.01540735 0.70679207 0.48062206]
  [0.54011005 0.15293922 0.44329893]]]


Create a 10x10 array with random values and find the minimum and maximum values

hint: min, max

In [45]:
array = np.random.random((10, 10))
print("Array:")
print(array)

Array:
[[0.4192484  0.76077828 0.46054919 0.41220322 0.08804392 0.53391332
  0.04065479 0.14565103 0.22172767 0.66353715]
 [0.61486586 0.07820162 0.38382279 0.84271845 0.16966554 0.7024445
  0.06944383 0.22716325 0.58519766 0.94587576]
 [0.16922802 0.74896672 0.36084932 0.79923696 0.90915289 0.76480658
  0.88264871 0.70438925 0.70603879 0.90712236]
 [0.47953785 0.50090235 0.52927289 0.13480516 0.6825749  0.9819378
  0.07532269 0.37185141 0.94336783 0.06054071]
 [0.16963774 0.41659167 0.70341272 0.79738862 0.89866739 0.13406603
  0.68262082 0.73304145 0.15225565 0.43204436]
 [0.28960682 0.53488009 0.6588696  0.78787519 0.3765018  0.30739189
  0.41393479 0.03476261 0.94792788 0.31582821]
 [0.20316555 0.65263145 0.69051373 0.81394327 0.69741159 0.58185733
  0.16955649 0.1799659  0.87251342 0.54191109]
 [0.30083355 0.85006732 0.85562182 0.51318896 0.87420603 0.87972691
  0.83250737 0.38309894 0.26026483 0.50538166]
 [0.22268814 0.44119106 0.58248857 0.09186037 0.06923462 0.36085969
  0.964

In [46]:
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.0014492628811973995
Maximum value: 0.9819377954539408


 Create a random vector of size 30 and find the mean value

hint: mean

In [47]:
vector = np.random.random(30)

print("Random Vector:")

print(vector)

Random Vector:
[0.69152696 0.98214607 0.38100912 0.67116582 0.2047102  0.01966242
 0.96000569 0.72872303 0.86930621 0.59398232 0.67624272 0.76441384
 0.96313657 0.17468454 0.28706563 0.86405802 0.7680313  0.68817829
 0.98425849 0.61953789 0.77127046 0.12230892 0.83719182 0.73127195
 0.56208164 0.82938429 0.34345617 0.47514753 0.5432327  0.34062693]


In [48]:
mean_value = np.mean(vector)

print("Mean value:", mean_value)

Mean value: 0.6149272509142303


Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

hint: np.diag

In [49]:
values = [1, 2, 3, 4]
matrix = np.diag(values, k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Normalize a 5x5 random matrix

hint: (x -mean)/std

In [50]:
matrix = np.random.random((5, 5))

mean = np.mean(matrix)
std = np.std(matrix)

normalized_matrix = (matrix - mean) / std

print(normalized_matrix)


[[-1.10012465 -0.76394298  0.11151729  1.20366152  0.3946426 ]
 [-0.13918488 -1.68738986 -0.56664967 -0.24090271 -0.6213454 ]
 [ 1.0473198   1.39499815  0.78527485  1.12494577  1.52317085]
 [-0.73548322 -1.18812543  0.927685   -1.70827045 -1.43152548]
 [ 1.04081436  0.74033766  0.6029218   0.22656231 -0.94090724]]


How to find common values between two arrays?

hint: np.intersect1d

In [51]:
first_sample = np.array([02.11, 08.30, 02.04])
second_sample = np.array([02.04, 02.11, 02.28])

common_values = np.intersect1d(first_sample, second_sample)

print(common_values)


[2.04 2.11]


Create a random vector of size 10 and sort it

hint: sort

In [52]:
random_vector = np.random.random(10)


sorted_it = np.sort(random_vector)


print(sorted_it)


[0.03712789 0.05059572 0.12760247 0.15672398 0.27478778 0.35260758
 0.47218683 0.60100493 0.63432357 0.89635797]


Create random vector of size 10 and replace the maximum value by 0

hint: argmax

In [53]:
vector = np.random.rand(10)

print(vector)

[0.2961091  0.86136259 0.28560233 0.21323454 0.75733255 0.22859324
 0.43649814 0.69881189 0.89328384 0.14706958]


In [54]:
max_value = np.argmax(vector)

vector[max_value] = 0

print (vector)

[0.2961091  0.86136259 0.28560233 0.21323454 0.75733255 0.22859324
 0.43649814 0.69881189 0.         0.14706958]


Subtract the mean of each row of a matrix 

hint: mean(axis=,keepdims=)

In [55]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

each_mean = np.mean(matrix, axis=1, keepdims=True)

deducted_matrix = matrix - each_mean

print(deducted_matrix)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


How to get the n largest values of an array

Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [56]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

largest_indices = np.argsort(Z)[-n:]

largest_values = Z[largest_indices]

print(largest_values)


[9995 9996 9997 9998 9999]


Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

hint: np.where

In [57]:
import numpy as np

matrix = np.random.randint(0, 10, size=(5, 3))

print("Original Matrix:")
print(matrix)

matrix = np.where(matrix > 4, matrix ** 2, matrix)

print("\nModified Matrix:")
print(matrix)


Original Matrix:
[[8 5 8]
 [1 6 0]
 [8 2 6]
 [0 1 3]
 [3 3 7]]

Modified Matrix:
[[64 25 64]
 [ 1 36  0]
 [64  2 36]
 [ 0  1  3]
 [ 3  3 49]]


In [58]:
import numpy as np

matrix = np.random.randint(0, 10, size=(5, 3))

print("Original Matrix:")
print(matrix)

matrix[matrix > 4] = matrix[matrix > 4] ** 2

print("Modified Matrix:")
print(matrix)


Original Matrix:
[[7 6 3]
 [5 2 8]
 [0 1 1]
 [0 4 5]
 [4 4 2]]
Modified Matrix:
[[49 36  3]
 [25  2 64]
 [ 0  1  1]
 [ 0  4 25]
 [ 4  4  2]]
